}name: Build and Deploy to AWS ECR + ECS

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-east-1
  AWS_ACCOUNT_ID: 190865905880

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar codigo
        uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login en Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ========================
      # BUILD Y PUSH
      # ========================

      - name: Build y push servicio1
        run: |
          docker build -t servicio1 ./ucmcloud/servicio1
          docker tag servicio1:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/servicio1:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/servicio1:latest

      - name: Build y push servicio2
        run: |
          docker build -t servicio2 ./ucmcloud/servicio2
          docker tag servicio2:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/servicio2:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/servicio2:latest

      - name: Build y push servicio3
        run: |
          docker build -t servicio3 ./ucmcloud/servicio3
          docker tag servicio3:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/servicio3:latest
          docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/servicio3:latest

      # ========================
      # DEPLOY ECS
      # ========================

      - name: Actualizar servicio1 en ECS
        run: |
          aws ecs update-service \
          --cluster clusterr \
          --service servicio1-task-service-mg7w51cm \
          --force-new-deployment

      - name: Actualizar servicio2 en ECS
        run: |
          aws ecs update-service \
          --cluster clusterr \
          --service servicio2-task-service-w8wqvknj \
          --force-new-deployment

      - name: Actualizar servicio3 en ECS
        run: |
          aws ecs update-service \
          --cluster clusterr \
          --service servicio3-task-service-6mfcr1tb \
          --force-new-deployment